spring: 
  profiles:
    active:
    - dev
--- 
server:
  port: 8001
spring: 
   profiles: dev
   application: 
    name: microservicecloud-config-dept-client
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://139.155.83.172:3306/cloudDB01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200 
mybatis:
  mapper-locations: classpath:mybatis/mapper/**.xml
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.qc.entities
 
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 
info:
  app.name: my-microservicecloud-springcloudconfig03-java1129
  company.name: www.my.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring: 
   profiles: test
   application: 
    name: microservicecloud-config-dept-client
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://139.155.83.172:3306/cloudDB02?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200  
  
mybatis:
  mapper-locations: classpath:mybatis/mapper/**.xml
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.qc.entities
 
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 
info:
  app.name: my-microservicecloud-springcloudconfig02
  company.name: www.my.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$